# Permalinks
#
permalink:           pretty

# Setup
title:               Swift++
tagline:             'Objective-C without the baggage of Swift'
description:         'An effort to build a Smalltalk-based compiler for the Swift environment.'
url:                 http://swiftpp.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              The Swift++ Project
  url:               https://twitter.com/swiftplusplus
  email:             swiftplusplus@gmail.com

# Custom vars
version:             1.0.0
